<?php
session_write_close();
G::LoadClass('pmFunctions');
require 'env.php';

$res = executeQuery('select count(*) cc from APPLICATION');
$count = $res[1]['cc'];


$sql = "SELECT APP_CACHE_VIEW.APP_UID,
APP_CACHE_VIEW.DEL_INDEX,
APP_CACHE_VIEW.DEL_LAST_INDEX,
APP_CACHE_VIEW.APP_NUMBER,
APP_CACHE_VIEW.APP_STATUS,
APP_CACHE_VIEW.USR_UID,
APP_CACHE_VIEW.PREVIOUS_USR_UID,
APP_CACHE_VIEW.TAS_UID,
APP_CACHE_VIEW.PRO_UID,
APP_CACHE_VIEW.DEL_DELEGATE_DATE,
APP_CACHE_VIEW.DEL_INIT_DATE, APP_CACHE_VIEW.DEL_FINISH_DATE, APP_CACHE_VIEW.DEL_TASK_DUE_DATE, APP_CACHE_VIEW.DEL_RISK_DATE, APP_CACHE_VIEW.DEL_THREAD_STATUS, APP_CACHE_VIEW.APP_THREAD_STATUS, APP_CACHE_VIEW.APP_TITLE, APP_CACHE_VIEW.APP_PRO_TITLE, APP_CACHE_VIEW.APP_TAS_TITLE, APP_CACHE_VIEW.APP_CURRENT_USER, APP_CACHE_VIEW.APP_DEL_PREVIOUS_USER, APP_CACHE_VIEW.DEL_PRIORITY, APP_CACHE_VIEW.DEL_DURATION, APP_CACHE_VIEW.DEL_QUEUE_DURATION, APP_CACHE_VIEW.DEL_DELAY_DURATION, APP_CACHE_VIEW.DEL_STARTED, APP_CACHE_VIEW.DEL_FINISHED, APP_CACHE_VIEW.DEL_DELAYED, APP_CACHE_VIEW.APP_CREATE_DATE, APP_CACHE_VIEW.APP_FINISH_DATE, APP_CACHE_VIEW.APP_UPDATE_DATE, APP_CACHE_VIEW.APP_OVERDUE_PERCENTAGE, APP_CACHE_VIEW.DEL_INIT_DATE, APP_CACHE_VIEW.TAS_UID, APP_CACHE_VIEW.PRO_UID,
CU.USR_UID AS USR_UID,
CU.USR_FIRSTNAME AS USR_FIRSTNAME,
CU.USR_LASTNAME AS USR_LASTNAME,
CU.USR_USERNAME AS USR_USERNAME,
APPDELCR.APP_TAS_TITLE AS APPDELCR_APP_TAS_TITLE,
USRCR.USR_UID AS USRCR_USR_UID,
USRCR.USR_FIRSTNAME AS USRCR_USR_FIRSTNAME,
USRCR.USR_LASTNAME AS USRCR_USR_LASTNAME,
USRCR.USR_USERNAME AS USRCR_USR_USERNAME
FROM APP_CACHE_VIEW
LEFT JOIN TASK ON (APP_CACHE_VIEW.TAS_UID=TASK.TAS_UID)
LEFT JOIN USERS CU ON (APP_CACHE_VIEW.USR_UID=CU.USR_UID)
LEFT JOIN APP_CACHE_VIEW APPDELCR ON (APP_CACHE_VIEW.APP_UID=APPDELCR.APP_UID AND APPDELCR.DEL_LAST_INDEX=1)
LEFT JOIN USERS USRCR ON (APPDELCR.USR_UID=USRCR.USR_UID)
WHERE (((((((APP_CACHE_VIEW.APP_STATUS='TO_DO' AND APP_CACHE_VIEW.DEL_FINISH_DATE IS NULL )
AND APP_CACHE_VIEW.APP_THREAD_STATUS='OPEN')
AND APP_CACHE_VIEW.DEL_THREAD_STATUS='OPEN')
 OR ((APP_CACHE_VIEW.APP_STATUS='DRAFT'
 AND APP_CACHE_VIEW.APP_THREAD_STATUS='OPEN')
 AND APP_CACHE_VIEW.DEL_THREAD_STATUS='OPEN'))
 OR (APP_CACHE_VIEW.APP_STATUS IN ('DRAFT','TO_DO')
 AND APP_CACHE_VIEW.APP_UID IN
 (SELECT DISTINCT APP_DELAY.APP_UID
 FROM   APP_DELAY
 WHERE  APP_DELAY.APP_UID = APP_CACHE_VIEW.APP_UID
 AND                       APP_DELAY.APP_DEL_INDEX = APP_CACHE_VIEW.DEL_INDEX
 AND                       (APP_DELAY.APP_DISABLE_ACTION_USER
 IS NULL OR APP_DELAY.APP_DISABLE_ACTION_USER = '0')
 AND                       APP_DELAY.APP_DELAY_UID
 IS NOT NULL
 AND                       APP_DELAY.APP_TYPE = 'PAUSE')))
 OR ((APP_CACHE_VIEW.APP_STATUS='CANCELLED'
 AND APP_CACHE_VIEW.DEL_THREAD_STATUS='CLOSED')
 AND APP_CACHE_VIEW.DEL_LAST_INDEX=1))
 OR (APP_CACHE_VIEW.APP_STATUS='COMPLETED'
 AND APP_CACHE_VIEW.DEL_LAST_INDEX=1))
 AND TASK.TAS_TYPE NOT IN ('WEBENTRYEVENT','END-MESSAGE-EVENT','START-MESSAGE-EVENT','INTERMEDIATE-THROW-MESSAGE-EVENT','INTERMEDIATE-CATCH-MESSAGE-EVENT')
 GROUP BY APP_CACHE_VIEW.APP_UID,APP_CACHE_VIEW.DEL_INDEX,APPDELCR.APP_TAS_TITLE, USRCR.USR_UID
 ORDER BY APP_CACHE_VIEW.APP_NUMBER DESC LIMIT 25
";

//2.x
//all
$sql1 = "SELECT *, APP_CACHE_VIEW.DEL_INIT_DATE, MAX(APP_CACHE_VIEW.DEL_INDEX) AS MAX_DEL_INDEX, CU.USR_FIRSTNAME AS USR_FIRSTNAME, CU.USR_LASTNAME AS USR_LASTNAME, CU.USR_USERNAME AS USR_USERNAME FROM APP_CACHE_VIEW LEFT JOIN USERS CU ON (APP_CACHE_VIEW.USR_UID=CU.USR_UID) WHERE APP_CACHE_VIEW.DEL_INDEX IN (2,2,2,2,1,2) GROUP BY APP_CACHE_VIEW.APP_UID ORDER BY APP_CACHE_VIEW.APP_NUMBER DESC LIMIT 20";
//by process
$sql2 = "SELECT *, APP_CACHE_VIEW.DEL_INIT_DATE, MAX(APP_CACHE_VIEW.DEL_INDEX) AS MAX_DEL_INDEX, CU.USR_FIRSTNAME AS USR_FIRSTNAME, CU.USR_LASTNAME AS USR_LASTNAME, CU.USR_USERNAME AS USR_USERNAME FROM APP_CACHE_VIEW LEFT JOIN USERS CU ON (APP_CACHE_VIEW.USR_UID=CU.USR_UID)
 WHERE APP_CACHE_VIEW.PRO_UID='".$processId."' AND
 APP_CACHE_VIEW.DEL_INDEX IN (2,2,2,2,1,2) GROUP BY APP_CACHE_VIEW.APP_UID ORDER BY APP_CACHE_VIEW.APP_NUMBER DESC LIMIT 20";


//3.x
$sql1 = "SELECT APPLICATION.APP_NUMBER, APPLICATION.APP_UID, APPLICATION.APP_STATUS, APPLICATION.PRO_UID, APPLICATION.APP_CREATE_DATE, APPLICATION.APP_FINISH_DATE, APPLICATION.APP_UPDATE_DATE, APPLICATION.APP_TITLE, APP_DELEGATION.USR_UID, APP_DELEGATION.TAS_UID, APP_DELEGATION.DEL_INDEX, APP_DELEGATION.DEL_LAST_INDEX, APP_DELEGATION.DEL_DELEGATE_DATE, APP_DELEGATION.DEL_INIT_DATE, APP_DELEGATION.DEL_FINISH_DATE, APP_DELEGATION.DEL_TASK_DUE_DATE, APP_DELEGATION.DEL_RISK_DATE, APP_DELEGATION.DEL_THREAD_STATUS, APP_DELEGATION.DEL_PRIORITY, APP_DELEGATION.DEL_DURATION, APP_DELEGATION.DEL_QUEUE_DURATION, APP_DELEGATION.DEL_STARTED, APP_DELEGATION.DEL_DELAY_DURATION, APP_DELEGATION.DEL_FINISHED, APP_DELEGATION.DEL_DELAYED, APP_DELEGATION.DEL_DELAY_DURATION, USERS.USR_LASTNAME, USERS.USR_FIRSTNAME, USERS.USR_USERNAME, TASK.TAS_TITLE, PROCESS.PRO_TITLE FROM APP_DELEGATION LEFT JOIN APPLICATION ON (APP_DELEGATION.APP_NUMBER=APPLICATION.APP_NUMBER) LEFT JOIN APP_THREAD ON (APP_DELEGATION.DELEGATION_ID=APP_THREAD.DELEGATION_ID) LEFT JOIN USERS ON (APP_DELEGATION.USR_ID=USERS.USR_ID) LEFT JOIN PROCESS ON (APP_DELEGATION.PRO_ID=PROCESS.PRO_ID) LEFT JOIN TASK ON (APP_DELEGATION.TAS_ID=TASK.TAS_ID) WHERE APP_DELEGATION.DEL_THREAD_STATUS='OPEN' AND TASK.TAS_TYPE NOT IN ('WEBENTRYEVENT','END-MESSAGE-EVENT','START-MESSAGE-EVENT','INTERMEDIATE-THROW-MESSAGE-EVENT','INTERMEDIATE-CATCH-MESSAGE-EVENT') ORDER BY APPLICATION.APP_NUMBER DESC LIMIT 25";
$sql2 = "SELECT APPLICATION.APP_NUMBER, APPLICATION.APP_UID, APPLICATION.APP_STATUS, APPLICATION.PRO_UID, APPLICATION.APP_CREATE_DATE, APPLICATION.APP_FINISH_DATE, APPLICATION.APP_UPDATE_DATE, APPLICATION.APP_TITLE, APP_DELEGATION.USR_UID, APP_DELEGATION.TAS_UID, APP_DELEGATION.DEL_INDEX, APP_DELEGATION.DEL_LAST_INDEX, APP_DELEGATION.DEL_DELEGATE_DATE, APP_DELEGATION.DEL_INIT_DATE, APP_DELEGATION.DEL_FINISH_DATE, APP_DELEGATION.DEL_TASK_DUE_DATE, APP_DELEGATION.DEL_RISK_DATE, APP_DELEGATION.DEL_THREAD_STATUS, APP_DELEGATION.DEL_PRIORITY, APP_DELEGATION.DEL_DURATION, APP_DELEGATION.DEL_QUEUE_DURATION, APP_DELEGATION.DEL_STARTED, APP_DELEGATION.DEL_DELAY_DURATION, APP_DELEGATION.DEL_FINISHED, APP_DELEGATION.DEL_DELAYED, APP_DELEGATION.DEL_DELAY_DURATION, USERS.USR_LASTNAME, USERS.USR_FIRSTNAME, USERS.USR_USERNAME, TASK.TAS_TITLE, PROCESS.PRO_TITLE FROM APP_DELEGATION LEFT JOIN APPLICATION ON (APP_DELEGATION.APP_NUMBER=APPLICATION.APP_NUMBER) LEFT JOIN APP_THREAD ON (APP_DELEGATION.DELEGATION_ID=APP_THREAD.DELEGATION_ID) LEFT JOIN USERS ON (APP_DELEGATION.USR_ID=USERS.USR_ID) LEFT JOIN PROCESS ON (APP_DELEGATION.PRO_ID=PROCESS.PRO_ID) LEFT JOIN TASK ON (APP_DELEGATION.TAS_ID=TASK.TAS_ID) WHERE APP_DELEGATION.DEL_THREAD_STATUS='OPEN' AND PROCESS.PRO_ID=".$processIdNum." AND TASK.TAS_TYPE NOT IN ('WEBENTRYEVENT','END-MESSAGE-EVENT','START-MESSAGE-EVENT','INTERMEDIATE-THROW-MESSAGE-EVENT','INTERMEDIATE-CATCH-MESSAGE-EVENT') ORDER BY APPLICATION.APP_NUMBER DESC LIMIT 25";

$t = microtime(true);
executeQuery($sql1);
$search1 = (microtime(true)-$t)*1000;

$t = microtime(true);
executeQuery($sql2);
$search2 = (microtime(true)-$t)*1000;

echo json_encode(array('count'=>$count,'search1'=>$search1,'search2'=>$search2));
